/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 --shadows .\public\models\characters\Enemy.glb 
*/

import { useRef, useMemo, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { ThreeEvent, useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";
import { BufferGeometry, Material, Object3D, Skeleton } from "three";
import { Vector3 } from "yuka";

const Enemy = (props: {
  agentId: string;
  OnClicked?: (data: { position: Vector3; agentId: string }) => void;
  scale: number;
}) => {
  const ref = useRef();

  const { scene, materials, animations } = useGLTF(
    "./assets/models/characters/Enemy.glb"
  );
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone) as {
    nodes: {
      [key: string]: Object3D & {
        geometry?: BufferGeometry;
        skeleton: Skeleton;
      };
    };
    materials: { [key: string]: Material };
  };

  const { actions } = useAnimations(animations, ref);
  const [animation] = useState("Walk");

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => {
      actions[animation].fadeOut(0.5);
    };
  }, [animation]);

  const GotHit = (event: ThreeEvent<PointerEvent>) => {
    event.stopPropagation();
  };

  return (
    <group ref={ref} {...props} position-y={0} dispose={null}>
      <group name="Scene">
        <group name="Enemy" onPointerDown={GotHit}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <group name="Pink_Blob">
            <skinnedMesh
              name="Cube010"
              geometry={nodes.Cube010.geometry}
              material={materials.Pink_Main}
              skeleton={nodes.Cube010.skeleton}
            />
            <skinnedMesh
              name="Cube010_1"
              geometry={nodes.Cube010_1.geometry}
              material={materials.Pink_Secondary}
              skeleton={nodes.Cube010_1.skeleton}
            />
          </group>
          <group name="Pink_Blob001">
            <skinnedMesh
              name="Cube000"
              geometry={nodes.Cube000.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube000.skeleton}
            />
            <skinnedMesh
              name="Cube000_1"
              geometry={nodes.Cube000_1.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube000_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default Enemy;
useGLTF.preload("./assets/models/characters/Enemy.glb");
